version: '0.0.0-{build}'

image:
- Visual Studio 2017

platform:
- x64

configuration:
- Release
- Debug

matrix:
  fast_finish: true

before_build:
- cmake -G "Visual Studio 15 2017 Win64"

build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln
  verbosity: minimal
  parallel: true
